### ISSUE TITLE
Support public key authentication

### ISSUE THREAD

**Issue by jdwhite** [zb0th/homebridge-ssh#2]
Please add the ability to specify the path to a private key and the (optional) password to decrypt that key.  Thanks.

**Comment by zb0th** [comment]
Adding support for specifying the path to a private key should be doable as 'ssh-exec' supports it. But adding support for the (optional) password to decrypt that key may not be that easy, as from looking at the 'ssh-exec' code, it seems it doesn't have support for it.

I should be able to have time to make this change this week.

**Comment by jdwhite** [comment]
I don't see lack of decryption passphrase (should have said passphrase before) as an issue. I'd wager that most people who are using pubkey auth to perform automated/unattended tasks don't set a passphrase on the private key anyway. Thanks.

**Comment by zb0th** [comment]
Just added support for the key based auth.

**Comment by jdwhite** [comment]
Thanks. Much appreciated!
