### ISSUE TITLE
 Is it possible to assign scripts to rooms, scenarios a.s.o. immediately from configuration in homebridge-ssh?

### ISSUE THREAD

**Issue by mtk64** [zb0th/homebridge-ssh#9]
Would like to place my assignments of rooms etc. into my configuration management, because I had to reset my homekit configuration on ipad for several times, and all these asigments went lost.
My hope is to get this from homebridge ... but I do not know the architecture. 
if this data is only stored within apples homekit cloud it might be impossible...

**Comment by alguevara7** [comment]
This is not the responsibility of this plugin.

**Comment by mtk64** [comment]
Excuse me, I am not really experienced within homebridge interfacing and management.
Which solution is normally used to assign homebridge-ssh Services to rooms a.s.o.? 
how do you assign E.g.  "mp3 play Music" via batch to different rooms like kitchen or livingroom?
Any hint would be great!
kr Michael 

Von meinem iPhone gesendet
